### ISSUE TITLE
Getting AttributeError when calling breakpoint()

### ISSUE THREAD

**Issue by tedyu** [pdbpp/pdbpp#533]
On MacOS, I installed pdbpp:
```
$ pip install pdbpp
Collecting pdbpp
  Downloading pdbpp-0.11.6-py3-none-any.whl.metadata (25 kB)
Collecting fancycompleter>=0.11.0 (from pdbpp)
  Downloading fancycompleter-0.11.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pygments in /Users/zhihongyu/code/lib/python3.13/site-packages (from pdbpp) (2.19.1)
Downloading pdbpp-0.11.6-py3-none-any.whl (33 kB)
Downloading fancycompleter-0.11.1-py3-none-any.whl (11 kB)
Installing collected packages: fancycompleter, pdbpp
Successfully installed fancycompleter-0.11.1 pdbpp-0.11.6
```
I get the following error calling `breakpoint()`:
```
Traceback (most recent call last):
  File "/tmp/lru.py", line 22, in <module>
    breakpoint()
    ~~~~~~~~~~^^
  File "/Users/zhihongyu/code/lib/python3.13/site-packages/_pdbpp_path_hack/pdb.py", line 18, in <module>
    exec(compile(f.read(), pdb_path, "exec"))
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhihongyu/code/lib/python3.13/site-packages/pdbpp.py", line 2130, in <module>
    func = getattr(pdb, name)
AttributeError: module 'pdb' has no attribute 'itertools'
```
Here is my OS:
```
Darwin Zhihongs-Air-2.attlocal.net 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
```
I patched pdbpp.py around line 2130 to get over the above error.

**Comment by salty-horse** [comment]
I get this with 3.13.0, but it works fine with 3.13.3.

The [.0 version of pdb.py](https://github.com/python/cpython/blob/v3.13.0/Lib/pdb.py) doesn't import `itertools`.
The [.1 version](https://github.com/python/cpython/blob/v3.13.1/Lib/pdb.py) does import it. 

I suggest changing it to a soft `getattr(pdb, name, None)` and do nothing if the module isn't found - this should also future-proof it since there's no guarantee what `pdb.py` imports at the global scope.
